### ISSUE TITLE
macOS Monterey

### ISSUE THREAD

**Issue by MostafaRabia** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#10]
Is it save to download?
Thanks.

**Comment by Innoxious** [comment]
I have not tested yet. I believe it requires an OpenCore update. I will consider updating this or feel free to open a pull request 😀

**Comment by MostafaRabia** [comment]
I won't test it now after your comment, I don't have another laptop for testing and I use it for working.
So I will wait your update.

**Comment by Innoxious** [comment]
Hi, just letting you know I am working on this. I have updated OpenCore to 0.7.5 and successfully updated to Monterey but there are a handful of issues. I do not recommend updating yet.

Current issues (non-exhaustive because I haven't been testing everything yet):
- Audio doesn't work
- Bluetooth doesn't work
- Slow boot time

**Comment by Innoxious** [comment]
https://github.com/Innoxious/hackintosh-hp-840-g3-intel-ac8260#how-to-update-from-big-sur-1152

Let me know how it goes!

**Comment by MostafaRabia** [comment]
Is it good for working now?
I don't have any another laptop to work.

**Comment by Innoxious** [comment]
Seems fine to me, I would suggest upgrading on a weekend or holiday just in case anything goes wrong - you will have a chance to debug the issue. Anyways, please tread carefully if it is your only device for work. I cannot guarantee success, I am only sharing my success.

**Comment by MostafaRabia** [comment]
@Innoxious 
HI

Today I tried to install the monterey, It installed and restarted from this:
![image](https://user-images.githubusercontent.com/25965798/143718497-125bb412-789a-44f9-9466-07412180ba65.png)

But nothing else, rebooting for a few seconds then enter to big sur.
What's wrong?

Thanks.

**Comment by MostafaRabia** [comment]
@Innoxious 
Your success is my success,  Thanks!
