### ISSUE TITLE
Does OpenCore 0.7.4 work and Monterey?

### ISSUE THREAD

**Issue by KryptonGS** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#11]
Could you update your OpenCore to 0.7.4?

**Comment by Innoxious** [comment]
I intend to when I have free time 😅 I welcome you to update it and open a pull request here. Can't promise anything but I'm also excited to try Monterey.

**Comment by Innoxious** [comment]
Closing this in favour of #10
