### ISSUE TITLE
Internal EID reader don't work

### ISSUE THREAD

**Issue by HaCkEuR0ElItE** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#12]
Hi,

First, thanks a lot for your work :)

I have a question in regards to the internal EID reader, on my Elitebook 850 G3, it doesn't work. 

I don't if is normal because you don't have one? But is it possible to activate it ? The internal EID reader is very usefull and it's the only thing that's don't work with your EFI.

Again thanks for your work :)

**Comment by Innoxious** [comment]
Hey @HaCkEuR0ElItE 

I do have the smart card reader but I don't use it and don't have any way to test it. What would support for the reader look like on MacOS?

Unsure if someone else has figured it out yet.
