### ISSUE TITLE
No bluetooth

### ISSUE THREAD

**Issue by jordibadiag** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#17]
Hi, It's been impossible to enable bluetooth. Do you have the driver or efi?

**Comment by Innoxious** [comment]
![image](https://user-images.githubusercontent.com/5837038/179487441-696f33e2-72b7-4776-bc73-37f7041554cf.png)
![image](https://user-images.githubusercontent.com/5837038/179487508-d1a21e34-bcb3-4c96-828a-76a474e0eb7b.png)

Hi @jordibadiag, this EFI uses https://github.com/OpenIntelWireless/IntelBluetoothFirmware
see: https://github.com/Innoxious/hackintosh-hp-840-g3-intel-ac8260/tree/main/EFI/OC/Kexts/IntelBluetoothFirmware.kext/Contents

What bluetooth card is in your laptop?

**Comment by jordibadiag** [comment]
perfect, its seems that it works. Thanks so much!
Everything working 100%
