### ISSUE TITLE
Speakers not detected on Big Sur 11.3.1

### ISSUE THREAD

**Issue by jmrbob300** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#2]
Jack detection also does not work for 3.5mm headphones. Bluetooth devices work fine.

Thanks!

**Comment by Innoxious** [comment]
Hey @jmrbob300 can you try add `alcid=13` in your boot-args

https://github.com/Innoxious/hackintosh-hp-840-g3-intel-ac8260/blob/37f8fd901b3802bd4b46267b54662a1269cec9fe/EFI/OC/config.plist#L1641

Let me know how you get on :)

**Comment by jmrbob300** [comment]
Thanks for the suggestion. I have tried editing the line in my config.plist and after reboot, still no luck. I added the suggested value to the string as shown below.

keepsyms=1 agdpmod=vit9696 darkwake=1 alcdelay=500 alcid=13
