### ISSUE TITLE
Is wifi fixed?

### ISSUE THREAD

**Issue by MostafaRabia** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#3]
Will be there fix for wifi issue?
big sur 11.4

**Comment by Innoxious** [comment]
Wifi is implemented by https://github.com/OpenIntelWireless/itlwm

It is still at reduced speed for now, totally fine for 1080p YouTube videos.

I'll be updating the kext as soon as they release a substantial version

**Comment by Innoxious** [comment]
@MostafaRabia I just updated AirportItlwm to latest - v2.0.0 and download speeds are much more respectable.

Upload speeds are still slow but I can't confirm if its due to OS/Kext because I do not dual boot Windows. Hope that helps :)
