### ISSUE TITLE
Complete tutorial for the installation of the hackintosh 

### ISSUE THREAD

**Issue by mabi87** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#4]
Hi,

I will greatfull if you can write a complete step by step tutorial on the installation of the hackintosh or if you can direct me to a video tutorial. 

Thanks.

**Comment by ghost** [comment]
Hey @mabi87 

While it's designed for a Dell Optiplex system, if you ignore/skip the vendor/machine specific instructions, you can use this tutorial instead. Really, really helped me personally. Just make sure you don't use the Optihack EFI folder, and substitute for the one contained in this repository :)

Really good luck (reach out to @Innoxious or I if you've any more queries!).

Chris <3

**Comment by ghost** [comment]
Just reread it, forgot to include the link 😔 
https://github.com/zearp/OptiHack/tree/v3.1

Sorry!

**Comment by Innoxious** [comment]
This is the most relevant and recent video I could find :) https://www.youtube.com/watch?v=43vP2qHGduU
