### ISSUE TITLE
Install Time.

### ISSUE THREAD

**Issue by CilekciGs** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#5]
Hello, When I initially boot up from the usb and click install. The text reads "About 2 hours and 20 minutes remaining" And the bar is about 75 percent full and stuck.

**Comment by CilekciGs** [comment]
and goes up to 8 hours after couple of minutes.

**Comment by Innoxious** [comment]
Huh that's weird 🤔. I installed with a external SSD on the USB-C port, it took about 20 minutes iirc. Are you able to try different devices?

**Comment by CilekciGs** [comment]
Unfortunately no, I just can't Install BigSur. I tried your config just to make sure that I didn't do something wrong. But it didn't help either I Have an OK connection (50 Mbps Download)
I don't think it's because of that. I tried Ethernet too But still same, I guess I am the only one having this issue I will ask this question on r/Hacintosh. Thank you for your assistance.

**Comment by CilekciGs** [comment]
https://www.reddit.com/r/hackintosh/comments/p9f06n/installing_takes_forever_with_good_connection/

**Comment by CilekciGs** [comment]
Can You please bump it ?
