### ISSUE TITLE
Upgrade laptop

### ISSUE THREAD

**Issue by MostafaRabia** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#7]
I will upgrade my laptop by adding M.2 256GB, Then re-install mac on it, Then add 1TB HDD.

Will mac read HDD with M.2?
Or will be there a problem?

Thanks.

**Comment by Innoxious** [comment]
Hey @MostafaRabia,

There will not be a problem. You should take advantage of dual booting too because it is much easier with two drives.

https://dortania.github.io/OpenCore-Multiboot/empty/diffdisk.html

**Comment by MostafaRabia** [comment]
Hey @Innoxious 
Thanks for your replay.
What I'm going to do is macOS in M.2, Alongside windows 10 in the same M.2, Is this good?
I don't need the windows to be in HDD.

If not work, So will macOS read 1TB HDD and use it normally? I will think in vm to install windows inside macOS.

**Comment by Innoxious** [comment]
@MostafaRabia information on Open Core: https://dortania.github.io/OpenCore-Multiboot/empty/samedisk.html

You will need to format the 1TB drive with a format compatible with Windows and MacOS

**Comment by MostafaRabia** [comment]
@Innoxious 
Very thanks, But I have last question, 
"with a format compatible with Windows and MacOS"
What is that format?

**Comment by Innoxious** [comment]
@MostafaRabia should be FAT32 or exFAT I believe.
