### ISSUE TITLE
Laptop restarts again and again from installation apple logo screen

### ISSUE THREAD

**Issue by zapaaris** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#8]
Is there any BIOS issue? i have make BIOS configuration according to the snapshots provided here, but on installation screen laptop restarts again and again. Please guide me about where issue may arise?

**Comment by Innoxious** [comment]
Hi @zapaaris can you describe what stage you are at?

i.e. is this before installation, or after? Is it restarting the laptop only or does a full shutdown work?

**Comment by Innoxious** [comment]
Hi @zapaaris is this after installation or during? Do you get into MacOS at all? And what version are you installing?

**Comment by zapaaris** [comment]
Hi
Thanks dear for reply
Meanwhile i got the efi from another tutorial video description link on
YouTube that worked perfectly well.

The efi you provided didn’t work, i was installing Big Sur on the same
model HP 840 G3 6600 processor. While using your efi, just at the starting
of installation, when display appears with apple logo and loading bar
(after open core selection menu at booting), laptop restarted again and
again.

Em new to hackintosh, it may be any reason…
Thanks for your reply
Regards
-- 
<https://www.freelancer.com/affiliates/email/21864801/>
Zaheer Ahmed <https://www.freelancer.com/affiliates/email/21864801/>

Java | PHP | C# | C | Web/Desktop/Mobile Developer
Lecturer Computer Science

P: +923218873366

E: ***@***.***
A:

 DISTT CHAKWAL, 48800, Pakistan
Hire me on Freelancer.com
<https://www.freelancer.com/affiliates/email/21864801/>
